network_scanner/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('nmap_application.urls')),
    path('admin/', admin.site.urls),
]

nmap_application/urls.py
from django.urls import path

from . import views

# In the urls if the action succeded returns to all automatically
app_name='network_scanner'
urlpatterns = [
    path('network-scanner/', views.ScannerView.as_view(), name='form_scanner_view'),
    path('perform-scan/', views.ScannerView.as_view(), name='post_form_scanner'),
    path('scanner-history/<str:type>', views.ScannerHistoryListView.as_view(), name='scanner_type'),
    path('scanner-history/<int:scanner_history_id>/host', views.HostListView.as_view(), name='host_list'),
    path('scanner-history/<int:scanner_history_id>/host/<int:host_id>/os_match', views.OperativeSystemMatchListView.as_view(), name='os_matches_list'),
    path('scanner-history/<int:scanner_history_id>/host/<int:host_id>/ports', views.PortListView.as_view(), name='host_ports_list'),
]

nmap_application/models.py
from django.db import models

# Source: Model field reference https://docs.djangoproject.com/en/3.1/ref/models/fields/#module-django.db.models.fields

class Host(models.Model):

    IP = models.GenericIPAddressField()

    mac_address = models.CharField(
        max_length=20,
        null=True
    )

    created_on = models.DateTimeField(
        auto_now_add=True,
        help_text="Date and time when the register was created"
    )

    updated_on = models.DateTimeField(
        auto_now=True,
        help_text="Date and time when the register was updated"
    )

    class Meta:
        ordering = ['-created_on']

class OperativeSystemMatch(models.Model):

    name = models.CharField(
        max_length=255
    )

    accuracy = models.PositiveSmallIntegerField()

    line = models.PositiveSmallIntegerField()

    host = models.ForeignKey(
        Host,
        on_delete=models.CASCADE,
        related_name='host_os_match'
    )

    created_on = models.DateTimeField(
        auto_now_add=True,
        help_text="Date and time when the register was created"
    )

    updated_on = models.DateTimeField(
        auto_now=True,
        help_text="Date and time when the register was updated"
    )

    class Meta:
        ordering = ['-created_on']

class OperativeSystemClass(models.Model):

    operative_system_match = models.OneToOneField(
        OperativeSystemMatch,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='os_match_class'
    )

    type = models.CharField(
        max_length=255
    )

    vendor = models.CharField(
        max_length=255
    )

    operative_system_family = models.CharField(
        max_length=255
    )

    operative_system_generation = models.CharField(
        max_length=255
    )

    accuracy = models.PositiveSmallIntegerField()

    created_on = models.DateTimeField(
        auto_now_add=True,
        help_text="Date and time when the register was created"
    )

    updated_on = models.DateTimeField(
        auto_now=True,
        help_text="Date and time when the register was updated"
    )

class Port(models.Model):

    protocol = models.CharField(
        max_length=255
    )

    portid = models.PositiveSmallIntegerField()

    state = models.CharField(
        max_length=255
    )

    reason = models.CharField(
        max_length=255
    )

    reason_ttl = models.PositiveSmallIntegerField()

    host = models.ForeignKey(
        Host,
        on_delete=models.CASCADE,
        related_name='host_port'
    )

    created_on = models.DateTimeField(
        auto_now_add=True,
        help_text="Date and time when the register was created"
    )

    updated_on = models.DateTimeField(
        auto_now=True,
        help_text="Date and time when the register was updated"
    )

    class Meta:
        ordering = ['-created_on']

class PortService(models.Model):

    port = models.OneToOneField(
        Port,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='port_service'
    )

    name = models.CharField(
        max_length=255,
        null=True
    )

    product = models.CharField(
        max_length=255,
        null=True
    )

    extra_info = models.CharField(
        max_length=255,
        null=True
    )

    hostname = models.CharField(
        max_length=255,
        null=True
    )

    operative_system_type = models.CharField(
        max_length=255,
        null=True
    )

    method = models.CharField(
        max_length=255,
        null=True
    )

    conf = models.PositiveSmallIntegerField()

    created_on = models.DateTimeField(
        auto_now_add=True,
        help_text="Date and time when the register was created"
    )

    updated_on = models.DateTimeField(
        auto_now=True,
        help_text="Date and time when the register was updated"
    )

class ScannerHistory(models.Model):

    target = models.GenericIPAddressField()

    hosts = models.ManyToManyField(
        Host,
        related_name='host_history'
    )

    # Choices for field type
    QUICK = 'QS'
    FULL = 'FS'
    TYPE_CHOICES = [
        (QUICK, 'Quick scan'),
        (FULL, 'Full scan'),
    ]

    type = models.CharField(
        max_length=2,
        choices=TYPE_CHOICES,
        default=QUICK,
    )

    created_on = models.DateTimeField(
        auto_now_add=True,
        help_text="Date and time when the register was created"
    )

    updated_on = models.DateTimeField(
        auto_now=True,
        help_text="Date and time when the register was updated"
    )

    class Meta:
        ordering = ['-id']

nmap_application/forms.py
from django import forms
from .models import ScannerHistory

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field, Fieldset,ButtonHolder
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions

# strip means to remove whitespace from the beginning and the end before storing the column
class ScannerForm(forms.Form):

    # Hint: this will need to be changed for use in the ads application :)
    class Meta:
        model = ScannerHistory
        fields = [
            'target',
            'type'
        ]

    target = forms.CharField(
        required=True,
        max_length=20,
        min_length=7,
        strip=True
    )

    # Choices for field type
    QUICK = 'QS'
    FULL = 'FS'
    type = forms.ChoiceField(
        choices = (
            (QUICK, "Quick scan"),
            (FULL, "Full scan")
        ),
        widget = forms.RadioSelect,
        initial = 'QS',
    )

# https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other
# https://gist.github.com/maraujop/1838193

nmap_application/views.py
from django.http import HttpResponse
from django.http.response import JsonResponse

from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView

from .forms import ScannerForm

from .models import (
    Host,
    OperativeSystemMatch,
    OperativeSystemClass,
    Port,
    PortService,
    ScannerHistory
)

from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse, resolve
from django.views import View

from .scanners import NmapScanner, ScapyScanner

from django.db.models import F

from django.http import HttpResponse

import json
class ScannerView(View, NmapScanner, ScapyScanner):

    model = ScannerHistory
    template_name = "nmap_application/scanner_form.html"

    def get(self, request) :

        scanner_form = ScannerForm()

        context = {
            'scanner_form': scanner_form
        }

        return render(request, self.template_name, context)

    def post(self, request) :

        target = request.POST['target']
        type = request.POST['type']
        response = {}

        if type == 'QS':
            self.target = target
            self.save_quick_scan()
            response['success'] = True
        else:
            self.perform_full_scan_and_save(request.POST['target'])
            response['success'] = True

        return HttpResponse(json.dumps(response), content_type="application/json")
        # return redirect(reverse('network_scanner:form_scanner_view'))

class ScannerHistoryListView(ListView):

    model = ScannerHistory
    template_name = "nmap_application/scanner_history_list.html"

    def get(self, request, type) :

        scanner_history = ScannerHistory.objects.filter(type=type)

        context = {
            'scanner_history' : scanner_history
        }
        return render(request, self.template_name, context)

class HostListView(ListView):

    model = Host
    template_name = "nmap_application/scanner_history_host_list.html"

    def get(self, request, scanner_history_id):

        scanner_history = ScannerHistory.objects.get(pk=scanner_history_id)

        hosts = Host.objects.filter(host_history=scanner_history_id)

        context = {
            'hosts' : hosts,
            'scanner_history': scanner_history
        }
        return render(request, self.template_name, context)

class OperativeSystemMatchListView(ListView):

    model = OperativeSystemMatch
    template_name = "nmap_application/scanner_history_host_os_matches_list.html"

    def get(self, request, scanner_history_id, host_id):

        host = Host.objects.get(pk=host_id)

        """
        Denormalizing tables

        INNER JOIN, source: 
        https://stackoverflow.com/a/21360352/9655579

        Set alias for fields, source: 
        https://stackoverflow.com/a/46471483/9655579
        """
        operative_system_match = OperativeSystemMatch.objects.filter(
            host=host_id
        ).values(
            'id',
            'name',
            'accuracy',
            'line',
            'created_on',
            'os_match_class__type',
            'os_match_class__vendor',
            'os_match_class__operative_system_family',
            'os_match_class__operative_system_generation',
            'os_match_class__accuracy'
        ).annotate(
            os_id=F('id'),
            os_name=F('name'),
            os_accuracy=F('accuracy'),
            os_line=F('line'),
            os_created_on=F('created_on'),
            os_match_class_type=F('os_match_class__type'),
            os_match_class_vendor=F('os_match_class__vendor'),
            os_match_class_operative_system_family=F('os_match_class__operative_system_family'),
            os_match_class_operative_system_generation=F('os_match_class__operative_system_generation'),
            os_match_class_accuracy=F('os_match_class__accuracy'),
        )

        context = {
            'operative_system_matches' : operative_system_match,
            'host': host,
            'scanner_history_id': scanner_history_id
        }

        return render(request, self.template_name, context)


class PortListView(ListView):

    model = Port
    template_name = "nmap_application/scanner_history_host_ports.html"

    def get(self, request, scanner_history_id, host_id):

        host = Host.objects.get(pk=host_id)

        """
        Denormalizing tables

        INNER JOIN, source: 
        https://stackoverflow.com/a/21360352/9655579

        Set alias for fields, source: 
        https://stackoverflow.com/a/46471483/9655579
        """
        ports = Port.objects.filter(
            host=host_id
        ).values(
            'id',
            'protocol',
            'portid',
            'state',
            'reason',
            'reason_ttl',
            'created_on',
            'port_service__name',
            'port_service__product',
            'port_service__extra_info',
            'port_service__hostname',
            'port_service__operative_system_type',
            'port_service__method',
            'port_service__conf'
        ).annotate(
            port_id=F('id'),
            port_name=F('protocol'),
            port_accuracy=F('portid'),
            port_state=F('state'),
            port_reason=F('reason'),
            port_reason_ttl=F('reason_ttl'),
            port_created_on=F('created_on'),
            port_service_name=F('port_service__name'),
            port_service_product=F('port_service__product'),
            port_service_extra_info=F('port_service__extra_info'),
            port_service_hostname=F('port_service__hostname'),
            port_service_operative_system_type=F('port_service__operative_system_type'),
            port_service_method=F('port_service__method'),
            port_service_conf=F('port_service__conf'),
        )

        context = {
            'ports' : ports,
            'host': host,
            'scanner_history_id': scanner_history_id
        }

        return render(request, self.template_name, context)


# Useful link: base commands
# https://stackoverflow.com/a/3037137/9655579

nmap_application/templates/nmap_application/scanner_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
<br />
<div id="spinner"></div>

<p>
    {% load crispy_forms_tags %}
    <form method="post" action="{% url 'network_scanner:post_form_scanner' %}" id="scanner_form">
        {% csrf_token %}
        {{ scanner_form|crispy }}
        <input type="submit" value="Submit" class="btn btn-dark" id="scanner_button">
    </form>
</p>
<p>
    <a href="{% url 'network_scanner:scanner_type' 'QS' %}">See quick scan history</a>
</p>
<p>
    <a href="{% url 'network_scanner:scanner_type' 'FS' %}">See full scan history</a>
</p>
<!--https://stackoverflow.com/questions/1960240/jquery-ajax-submit-form-->
<!--https://django-crispy-forms.readthedocs.io/en/latest/crispy_tag_forms.html#ajax-validation-recipe-->
<script type="text/javascript">
    $( document ).ready(function() {
      $('#scanner_button').click(function (event) {
        event.preventDefault();
        var scanner_form = '#scanner_form';

        $.ajax({
            url: "{% url 'network_scanner:post_form_scanner' %}",
            type: "POST",
            data: $(scanner_form).serialize(),
            datatype: 'json',
            header: {'X-CSRFToken': '{% csrf_token %}'},
            beforeSend: function () {
                // Set spinner from https://getbootstrap.com/docs/4.4/components/spinners/
                $('#spinner').html('<div class="d-flex align-items-center"><strong>Scanning, please wait, this will take a while...</strong><div class="spinner-border ml-auto" role="status" aria-hidden="true" style="width: 3rem; height: 3rem;"></div></div>')
            },
            success: function(data) {
                if (!(data['success'])) {
                    // Here we replace the form, for the
                    alert("An error has occurred");
                }
                else {
                    // Here you can show the user a success message or do whatever you need
                    alert("The network has been scanned successfully");
                }
            },
            complete: function () {
                $('#spinner').empty(); //Remove child elements
            },
            error: function (xhr, ajaxOptions, thrownError) {
                console.log(xhr.responseText);
            }
        });
      });
     });
  </script>
{% endblock %}

nmap_application/templates/nmap_application/scanner_history_host_list.html
{% extends "base_bootstrap.html" %}

{% block content %}

<p>
  <a href="{% url 'network_scanner:scanner_type' scanner_history.type %}" class="btn btn-dark">Back</a>
</p>
<h5>
  <strong>Scanner</strong>
</h5>
<p>
  <strong>Target: </strong> {{ scanner_history.target }}
</p>
<p>
  <strong>Created on: </strong> {{ scanner_history.created_on }}
</p>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">IP</th>
      <th scope="col">Mac address</th>
      {% if scanner_history.type  == 'FS' %}
      <th scope="col">View OS matches</th>
      <th scope="col">View ports</th>
      {% endif %}
    </tr>
  </thead>
  <tbody>
  {% for host in hosts %}
    <tr>
      <th scope="row">{{ host.id }}</th>
      <td>{{ host.IP }}</td>
      <td>{{ host.mac_address }}</td>
      {% if scanner_history.type  == 'FS' %}
      <td>
        <a href="{% url 'network_scanner:os_matches_list' scanner_history.id host.id %}" class="btn btn-dark">View os matches</a>
      </td>
      <td>
        <a href="{% url 'network_scanner:host_ports_list' scanner_history.id host.id %}" class="btn btn-dark">View ports</a>
      </td>
      {% endif %}
    </tr>
  {% endfor %}
  </tbody>
</table>

{% endblock %}

nmap_application/templates/nmap_application/scanner_history_host_os_matches_list.html
{% extends "base_bootstrap.html" %}

{% block content %}

<p>
  <a href="{% url 'network_scanner:host_list' scanner_history_id %}" class="btn btn-dark">Back</a>
</p>
<h5>
  <strong>Host</strong>
</h5>
<p>
  <strong>IP: </strong> {{ host.IP }}
</p>
<p>
  <strong>Mac address: </strong> {{ host.mac_address }}
</p>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Accuracy</th>
      <th scope="col">Line</th>
      <th scope="col">Created on</th>
      <th scope="col">Type</th>
      <th scope="col">Vendor</th>
      <th scope="col">OS family</th>
      <th scope="col">OS generation</th>
      <th scope="col">OS accuracy</th>
    </tr>
  </thead>
  <tbody>
  {% for operative_system_match in operative_system_matches %}
    <tr>
      <th scope="row">{{ operative_system_match.os_id }}</th>
      <td>{{ operative_system_match.os_name }}</td>
      <td>{{ operative_system_match.os_accuracy }}</td>
      <td>{{ operative_system_match.os_line }}</td>
      <td>{{ operative_system_match.os_created_on }}</td>
      <td>{{ operative_system_match.os_match_class_type }}</td>
      <td>{{ operative_system_match.os_match_class_vendor }}</td>
      <td>{{ operative_system_match.os_match_class_operative_system_family }}</td>
      <td>{{ operative_system_match.os_match_class_operative_system_generation }}</td>
      <td>{{ operative_system_match.os_match_class_accuracy }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>

{% endblock %}

nmap_application/templates/nmap_application/scanner_history_host_ports.html
{% extends "base_bootstrap.html" %}

{% block content %}

<p>
  <a href="{% url 'network_scanner:host_list' scanner_history_id %}" class="btn btn-dark">Back</a>
</p>
<h5>
  <strong>Host</strong>
</h5>
<p>
  <strong>IP: </strong> {{ host.IP }}
</p>
<p>
  <strong>Mac address: </strong> {{ host.mac_address }}
</p>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Protocol</th>
      <th scope="col">Port id</th>
      <th scope="col">State</th>
      <th scope="col">Reason</th>
      <th scope="col">Reason ttl</th>
      <th scope="col">Created on</th>
      <th scope="col">Port service name</th>
      <th scope="col">Port service product</th>
      <th scope="col">Port service extra info</th>
      <th scope="col">Port service hostname</th>
      <th scope="col">Port service operative system type</th>
      <th scope="col">Port service method</th>
      <th scope="col">Port service conf</th>
    </tr>
  </thead>
  <tbody>
  {% for port in ports %}
    <tr>
      <th scope="row">{{ port.port_id }}</th>
      <td>{{ port.port_name }}</td>
      <td>{{ port.port_accuracy }}</td>
      <td>{{ port.port_state }}</td>
      <td>{{ port.port_reason }}</td>
      <td>{{ port.port_reason_ttl }}</td>
      <td>{{ port.port_created_on }}</td>
      <td>{{ port.port_service_name }}</td>
      <td>{{ port.port_service_product }}</td>
      <td>{{ port.port_service_extra_info }}</td>
      <td>{{ port.port_service_hostname }}</td>
      <td>{{ port.port_service_operative_system_type }}</td>
      <td>{{ port.port_service_method }}</td>
      <td>{{ port.port_service_conf }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>

{% endblock %}

nmap_application/templates/nmap_application/scanner_history_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
<p>
  <a href="{% url 'network_scanner:form_scanner_view' %}" class="btn btn-dark">Back</a>
</p>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Target</th>
      <th scope="col">Created on</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  {% for scanner in scanner_history %}
    <tr>
      <th scope="row">{{ scanner.id }}</th>
      <td>{{ scanner.target }}</td>
      <td>{{ scanner.created_on }}</td>
      <td>
        <a href="{% url 'network_scanner:host_list' scanner.id %}" class="btn btn-dark">View hosts</a>
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>

{% endblock %}